#!/usr/bin/env bash
#Configures an Nginx server to listen on port 80

#remove default nginx config file
rm /etc/nginx/sites-enabled/default

#Configure nginx to listen on port 80 for all active IPV4 IPs
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

#restart nginx
service nginx restart
