#!/usr/bin/env bash
#configures an nginx server to listen on port 80

ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

service nginx start #restart nginx

kill "$(pgrep 'nginx' | head -1)" #terminates the first nginx PID
