#!/usr/bin/env bash
# Script that install nginx server and write content to the root.
sudo apt-get update -y
sudo apt-get install nginx -y
echo "Holberton School" | sudo tee /var/www/html/index.html
sudo service nginx start
